// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/permissions/*": {
    params: {
      "*": string;
    };
  };
  "/api/groups/*": {
    params: {
      "*": string;
    };
  };
  "/api/chat/*": {
    params: {
      "*": string;
    };
  };
  "/api/document/*": {
    params: {
      "*": string;
    };
  };
  "/api/upload/*": {
    params: {
      "*": string;
    };
  };
  "/api/stripe-webhook": {
    params: {};
  };
  "/api/billing/*": {
    params: {
      "*": string;
    };
  };
  "/workspace": {
    params: {};
  };
  "/workspace/delete-annotation/:docId/:id": {
    params: {
      "docId": string;
      "id": string;
    };
  };
  "/workspace/document-search": {
    params: {};
  };
  "/workspace/document/:id": {
    params: {
      "id": string;
    };
  };
  "/workspace/document/:id/chat/:chatId": {
    params: {
      "id": string;
      "chatId": string;
    };
  };
  "/workspace/document/:id/chat-create": {
    params: {
      "id": string;
    };
  };
  "/workspace/document/:id/save-annotation": {
    params: {
      "id": string;
    };
  };
  "/workspace/document-create": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/signup" | "/api/auth/*" | "/api/permissions/*" | "/api/groups/*" | "/api/chat/*" | "/api/document/*" | "/api/upload/*" | "/api/stripe-webhook" | "/api/billing/*" | "/workspace" | "/workspace/delete-annotation/:docId/:id" | "/workspace/document-search" | "/workspace/document/:id" | "/workspace/document/:id/chat/:chatId" | "/workspace/document/:id/chat-create" | "/workspace/document/:id/save-annotation" | "/workspace/document-create";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/signin";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/signup";
  };
  "routes/api.auth.ts": {
    id: "routes/api.auth";
    page: "/api/auth/*";
  };
  "routes/api.permissions.ts": {
    id: "routes/api.permissions";
    page: "/api/permissions/*";
  };
  "routes/api.groups.ts": {
    id: "routes/api.groups";
    page: "/api/groups/*";
  };
  "routes/api.chat.ts": {
    id: "routes/api.chat";
    page: "/api/chat/*";
  };
  "routes/api.document.ts": {
    id: "routes/api.document";
    page: "/api/document/*";
  };
  "routes/api.upload.ts": {
    id: "routes/api.upload";
    page: "/api/upload/*";
  };
  "routes/api.stripe-webhook.ts": {
    id: "routes/api.stripe-webhook";
    page: "/api/stripe-webhook";
  };
  "routes/api.billing.ts": {
    id: "routes/api.billing";
    page: "/api/billing/*";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/workspace" | "/workspace/delete-annotation/:docId/:id" | "/workspace/document-search" | "/workspace/document/:id" | "/workspace/document/:id/chat/:chatId" | "/workspace/document/:id/chat-create" | "/workspace/document/:id/save-annotation" | "/workspace/document-create";
  };
  "routes/delete-annotation.ts": {
    id: "routes/delete-annotation";
    page: "/workspace/delete-annotation/:docId/:id";
  };
  "routes/document-search.tsx": {
    id: "routes/document-search";
    page: "/workspace/document-search";
  };
  "routes/document.tsx": {
    id: "routes/document";
    page: "/workspace/document/:id" | "/workspace/document/:id/chat/:chatId" | "/workspace/document/:id/chat-create" | "/workspace/document/:id/save-annotation";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/workspace/document/:id/chat/:chatId";
  };
  "routes/chat-create.tsx": {
    id: "routes/chat-create";
    page: "/workspace/document/:id/chat-create";
  };
  "routes/save-annotation.ts": {
    id: "routes/save-annotation";
    page: "/workspace/document/:id/save-annotation";
  };
  "routes/document-create.tsx": {
    id: "routes/document-create";
    page: "/workspace/document-create";
  };
};